---
apiVersion: v1
kind: Secret
metadata:
  name: eco-office-secrets
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: supersecretpassword
  POSTGRES_DB: ecooffice
  JWT_SECRET: my-super-secret-jwt-key
  DATABASE_URL: postgresql://postgres:supersecretpassword@postgres-service:5432/ecooffice

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: eco-office-secrets
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app-deployment
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-app
          image: qwertyssd/eco-office-backend:latest 
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: eco-office-secrets
          env:
            - name: PORT
              value: "3000"
      
         
          volumeMounts:
            - name: uploads-vol
              mountPath: /app/uploads
            - name: backups-vol
              mountPath: /app/backups
      volumes:
        - name: uploads-vol
          emptyDir: {}
        - name: backups-vol
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: backend-app-service
spec:
  type: LoadBalancer 
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-app-deployment
  minReplicas: 2
  maxReplicas: 10 
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60 
